app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Website Routes
|--------------------------------------------------------------------------
|
| Routes that will be used on the Website Front-end
| part of the website
|
*/

Route::get('login', function()
{
    // just a shortcut to redirecto /login into /manage/login
    return Redirect::route('manage.login');
});

/*
|--------------------------------------------------------------------------
| CMS Routes
|--------------------------------------------------------------------------
|
| Routes that will be used on the CMS part of the website,
| most routes used by the CMS will have a prefix of /manage
|
*/

Route::group(array('prefix' => 'manage'), function()
{
    Route::get('/', function()
    {
        if (Auth::guest())
        {
            return Redirect::route('manage.login');
        }
        else
        {
            return Redirect::route('manage.home');
        }
    });

    Route::get('login', array(
        'as'   => 'manage.login',
        'uses' => 'CMSController@login'
    ));

    Route::post('login', array(
        'as'   => 'manage.postLogin',
        'uses' => 'CMSController@userLogin'
    ));

    Route::get('logout', array(
        'as'   => 'manage.logout',
        'uses' => 'CMSController@userLogout'
    ));

    Route::group(array('before' => 'auth'), function()
    {
        Route::get('home', array(
            'as'   => 'manage.home',
            'uses' => 'CMSController@home'
        ));

        Route::get('profile', array(
            'as'   => 'manage.profile',
            'uses' => 'UsersController@showProfile'
        ));

        Route::get('profile/edit', array(
            'as'   => 'manage.profile-edit',
            'uses' => 'UsersController@editProfile'
        ));

        // Filter first if user is Visitor
        Route::when('manage/settings/create', 'ifVisitor');
        Route::when('manage/settings/*/edit', 'ifVisitor');
        Route::when('manage/dear-bossing/create', 'ifVisitor');
        Route::when('manage/dear-bossing/*/edit', 'ifVisitor');
        Route::when('manage/homepage-sliders/create', 'ifVisitor');
        Route::when('manage/homepage-sliders/*/edit', 'ifVisitor');
        Route::when('manage/badges/create', 'ifVisitor');
        Route::when('manage/badges/*/edit', 'ifVisitor');
        Route::when('manage/ingredients/create', 'ifVisitor');
        Route::when('manage/ingredients/*/edit', 'ifVisitor');
        Route::when('manage/procedures/create', 'ifVisitor');
        Route::when('manage/procedures/*/edit', 'ifVisitor');
        Route::when('manage/ratings/create', 'ifVisitor');
        Route::when('manage/ratings/*/edit', 'ifVisitor');
        Route::when('manage/products/create', 'ifVisitor');
        Route::when('manage/products/*/edit', 'ifVisitor');
        Route::when('manage/recipes/create', 'ifVisitor');
        Route::when('manage/recipes/*/edit', 'ifVisitor');

        Route::group(array('before' => 'isSuperAdmin'), function()
        {
            Route::resource('users', 'UsersController');
        });

        Route::resource('settings', 'SettingsController');
        Route::resource('dear-bossing', 'DearBossingController');
        Route::resource('homepage-sliders', 'HomepageSliderController');
        Route::resource('badges', 'BadgesController');
        Route::resource('ingredients', 'IngredientsController');
        Route::resource('procedures', 'ProceduresController');
        Route::resource('ratings', 'RatingsController');
        Route::resource('products', 'ProductsController');
        Route::resource('recipes', 'RecipesController');
        Route::resource('categories', 'CategoriesController');

        Route::group(array('prefix' => 'ajax'), function()
        {
            Route::get('users', array(
                'as'   => 'ajax.users',
                'uses' => 'UsersController@getDatatable'));
            Route::get('dear-bossing', array(
                'as'   => 'ajax.dear-bossing',
                'uses' => 'DearBossingController@getDatatable'));
            Route::get('settings', array(
                'as'   => 'ajax.settings',
                'uses' => 'SettingsController@getDatatable'));
            Route::get('homepage-slider', array(
                'as'   => 'ajax.homepage-slider',
                'uses' => 'HomepageSliderController@getDatatable'));
            Route::get('product', array(
                'as'   => 'ajax.product',
                'uses' => 'ProductsController@getDatatable'));
            Route::get('recipe', array(
                'as'   => 'ajax.recipe',
                'uses' => 'RecipesController@getDatatable'));
            Route::get('category', array(
                'as'   => 'ajax.category',
                'uses' => 'CategoriesController@getDatatable'));
        });
    });
});

app/views/cms/templates/sections/datatable.blade.php
<table id="{{ $id }}" class="{{ $class }}">
    <colgroup>
        @for ($i = 0; $i < count($columns); $i++)
        <col class="con{{ $i }}" />
        @endfor
    </colgroup>
    <thead>
    <tr>
        @foreach($columns as $i => $c)
        <th align="center" valign="middle" class="head{{ $i }}">{{ $c }}</th>
        @endforeach
    </tr>
    </thead>
    <tbody>
    @foreach($data as $d)
    <tr>
        @foreach($d as $dd)
        <td>{{ $dd }}</td>
        @endforeach
    </tr>
    @endforeach
    </tbody>
</table>

@if (!$noScript)
    @include('datatable::javascript', array('id' => $id, 'options' => $options, 'callbacks' =>  $callbacks))
@endif

app/views/cms/templates/sections/sidebar.blade.php
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="{{ URL::route('manage.home') }}"><i class="fa fa-home fa-fw"></i> Home</a>
                </li>
                @if (Auth::user()->isSuperAdmin())
                    <li>
                        <a href="{{ URL::route('manage.users.index') }}"><i class="fa fa-group fa-fw"></i> Users<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{ URL::route('manage.users.index') }}">View All</a>
                            </li>
                            <li>
                                <a href="{{ URL::route('manage.users.create') }}">Add New</a>
                            </li>
                        </ul><!-- /.nav-second-level -->
                    </li>
                @endif

                <li>
                    <a href="{{ URL::route('manage.dear-bossing.index') }}"><i class="fa fa-briefcase fa-fw"></i> Dear Bossing<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ URL::route('manage.dear-bossing.index') }}">View All</a>
                        </li>
                        <li  class="{{ Auth::user()->isVisitor() ? 'hidden' : '' }}">
                            <a href="{{ URL::route('manage.dear-bossing.create') }}">Add New</a>
                        </li>
                    </ul><!-- /.nav-second-level -->
                </li>

                <li>
                    <a href="{{ URL::route('manage.settings.index') }}"><i class="fa fa-gear fa-fw"></i> Settings<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ URL::route('manage.settings.index') }}">View All</a>
                        </li>
                        <li class="{{ Auth::user()->isVisitor() ? 'hidden' : '' }}">
                            <a href="{{ URL::route('manage.settings.create') }}">Add New</a>
                        </li>
                    </ul><!-- /.nav-second-level -->
                </li>

                <li>
                    <a href="{{ URL::route('manage.homepage-sliders.index') }}"><i class="fa fa-sliders fa-fw"></i> Homepage Sliders<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ URL::route('manage.homepage-sliders.index') }}">View All</a>
                        </li>
                        <li class="{{ Auth::user()->isVisitor() ? 'hidden' : '' }}">
                            <a href="{{ URL::route('manage.homepage-sliders.create') }}">Add New</a>
                        </li>
                    </ul><!-- /.nav-second-level -->
                </li>

                <li>
                    <a href="{{ URL::route('manage.homepage-sliders.index') }}"><i class="fa fa-cubes fa-fw"></i> Products<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ URL::route('manage.products.index') }}">View All</a>
                        </li>
                        <li class="{{ Auth::user()->isVisitor() ? 'hidden' : '' }}">
                            <a href="{{ URL::route('manage.products.create') }}">Add New</a>
                        </li>
                    </ul><!-- /.nav-second-level -->
                </li>

                <li>
                    <a href="{{ URL::route('manage.homepage-sliders.index') }}"><i class="fa fa-list fa-fw"></i> Recipes<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ URL::route('manage.recipes.index') }}">View All</a>
                        </li>
                        <li class="{{ Auth::user()->isVisitor() ? 'hidden' : '' }}">
                            <a href="{{ URL::route('manage.recipes.create') }}">Add New</a>
                        </li>
                    </ul><!-- /.nav-second-level -->
                </li>

                <li>
                    <a href="{{ URL::route('manage.categories.index') }}"><i class="fa fa-tags fa-fw"></i> Categories<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ URL::route('manage.categories.index') }}">View All</a>
                        </li>
                        <li class="{{ Auth::user()->isVisitor() ? 'hidden' : '' }}">
                            <a href="{{ URL::route('manage.categories.create') }}">Add New</a>
                        </li>
                    </ul><!-- /.nav-second-level -->
                </li>

            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

app/views/cms/templates/sections/topbar.blade.php
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ URL::route('manage.home') }}">Namnam CMS</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{{ URL::route('manage.profile') }}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{{ URL::route('manage.logout') }}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->