app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Website Routes
|--------------------------------------------------------------------------
|
| Routes that will be used on the Website Front-end
| part of the website
|
*/

Route::get('login', function()
{
    // just a shortcut to redirecto /login into /manage/login
    return Redirect::route('manage.login');
});

/*
|--------------------------------------------------------------------------
| CMS Routes
|--------------------------------------------------------------------------
|
| Routes that will be used on the CMS part of the website,
| most routes used by the CMS will have a prefix of /manage
|
*/

Route::group(array('prefix' => 'manage'), function()
{
    Route::get('/', function()
    {
        if (Auth::guest())
        {
            return Redirect::route('manage.login');
        }
        else
        {
            return Redirect::route('manage.home');
        }
    });

    Route::get('login', array(
        'as'   => 'manage.login',
        'uses' => 'CMSController@login'
    ));

    Route::post('login', array(
        'as'   => 'manage.postLogin',
        'uses' => 'CMSController@userLogin'
    ));

    Route::get('logout', array(
        'as'   => 'manage.logout',
        'uses' => 'CMSController@userLogout'
    ));

    Route::group(array('before' => 'auth'), function()
    {
        Route::get('home', array(
            'as'   => 'manage.home',
            'uses' => 'CMSController@home'
        ));

        Route::get('profile', array(
            'as'   => 'manage.profile',
            'uses' => 'UsersController@showProfile'
        ));

        Route::get('profile/edit', array(
            'as'   => 'manage.profile-edit',
            'uses' => 'UsersController@editProfile'
        ));

        // Filter first if user is Visitor
        Route::when('manage/settings/create', 'ifVisitor');
        Route::when('manage/settings/*/edit', 'ifVisitor');
        Route::when('manage/dear-bossing/create', 'ifVisitor');
        Route::when('manage/dear-bossing/*/edit', 'ifVisitor');
        Route::when('manage/homepage-sliders/create', 'ifVisitor');
        Route::when('manage/homepage-sliders/*/edit', 'ifVisitor');
        Route::when('manage/badges/create', 'ifVisitor');
        Route::when('manage/badges/*/edit', 'ifVisitor');
        Route::when('manage/ingredients/create', 'ifVisitor');
        Route::when('manage/ingredients/*/edit', 'ifVisitor');
        Route::when('manage/procedures/create', 'ifVisitor');
        Route::when('manage/procedures/*/edit', 'ifVisitor');
        Route::when('manage/ratings/create', 'ifVisitor');
        Route::when('manage/ratings/*/edit', 'ifVisitor');
        Route::when('manage/products/create', 'ifVisitor');
        Route::when('manage/products/*/edit', 'ifVisitor');
        Route::when('manage/recipes/create', 'ifVisitor');
        Route::when('manage/recipes/*/edit', 'ifVisitor');

        Route::group(array('before' => 'isSuperAdmin'), function()
        {
            Route::resource('users', 'UsersController');
        });

        Route::resource('settings', 'SettingsController');
        Route::resource('dear-bossing', 'DearBossingController');
        Route::resource('homepage-sliders', 'HomepageSliderController');
        Route::resource('badges', 'BadgesController');
        Route::resource('ingredients', 'IngredientsController');
        Route::resource('procedures', 'ProceduresController');
        Route::resource('ratings', 'RatingsController');
        Route::resource('products', 'ProductsController');
        Route::resource('recipes', 'RecipesController');
        Route::resource('categories', 'CategoriesController');

        Route::group(array('prefix' => 'ajax'), function()
        {
            Route::get('users', array(
                'as'   => 'ajax.users',
                'uses' => 'UsersController@getDatatable'));
            Route::get('dear-bossing', array(
                'as'   => 'ajax.dear-bossing',
                'uses' => 'DearBossingController@getDatatable'));
            Route::get('settings', array(
                'as'   => 'ajax.settings',
                'uses' => 'SettingsController@getDatatable'));
            Route::get('homepage-slider', array(
                'as'   => 'ajax.homepage-slider',
                'uses' => 'HomepageSliderController@getDatatable'));
            Route::get('product', array(
                'as'   => 'ajax.product',
                'uses' => 'ProductsController@getDatatable'));
            Route::get('recipe', array(
                'as'   => 'ajax.recipe',
                'uses' => 'RecipesController@getDatatable'));
            Route::get('category', array(
                'as'   => 'ajax.category',
                'uses' => 'CategoriesController@getDatatable'));
        });
    });
});

app/models/Procedure.php
<?php

class Procedure extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		// 'title' => 'required'
	];

	// Don't forget to fill this array
	protected $fillable = ['name','item'];

}

app/controllers/ProceduresController.php
<?php

class ProceduresController extends \BaseController {

	/**
	 * Display a listing of procedures
	 *
	 * @return Response
	 */
	public function index()
	{
		$procedures = Procedure::all();

		return View::make('procedures.index', compact('procedures'));
	}

	/**
	 * Show the form for creating a new procedure
	 *
	 * @return Response
	 */
	public function create()
	{
		$recipe = Recipe::lists('recipe_name', 'id');
		return View::make('procedures.create')
		->with('recipes', $recipe);
	}

	/**
	 * Store a newly created procedure in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make($data = Input::all(), Procedure::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		
		$data = Input::all();
        $new_procedures = new Procedure;
        $new_procedures->recipe_id = $data['recipe'];
        $new_procedures->name = $data['name'];
        $new_procedures->item = $data['item'];
        $new_procedures->save();

		return Redirect::route('manage.procedures.index');
	}

	/**
	 * Display the specified procedure.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$procedure = Procedure::findOrFail($id);

		return View::make('procedures.show', compact('procedure'));
	}

	/**
	 * Show the form for editing the specified procedure.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$procedure = Procedure::find($id);
        $recipe = Recipe::find($procedure->recipe_id);
        if(Session::has('recipe_id'))
        {
            $data = Session::all();
            return View::make('procedures.edit', compact('procedure'))
            ->with('recipe', $recipe)
            ->with('procedures_mode', 'true')
            ->with('recipe_id', $data['recipe_id']);
        }
		return View::make('procedures.edit', compact('procedure'))
		->with('recipe', $recipe);
	}

	/**
	 * Update the specified procedure in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$procedure = Procedure::findOrFail($id);
        $data = Input::all();
        if(Input::has('recipe_id'))
        {
            $recipe_id = $data['recipe_id'];
            unset($data['recipe_id']);
        }
		$validator = Validator::make($data, Procedure::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		$procedure->update($data);

        if(isset($recipe_id))
        {
            return Redirect::route('manage.recipes.create')
                        ->with('ingredients_mode', 'true')
                        ->with('recipe_id', $recipe_id);
        }

		return Redirect::route('manage.procedures.index');
	}

	/**
	 * Remove the specified procedure from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Procedure::destroy($id);

		return Redirect::route('procedures.index');
	}

}

app/views/procedures/create.blade.php
@extends('cms.templates.master')

{{-- TITLE : templates.master --}}
@section('title')
<title>Namnam CMS - Create Procdure</title>
@stop

{{-- CONTENT AREA : templates.master --}}
@section('content')

    @if($errors->has())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
    @endif

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Create Procedure</h1>
            <div class="row">
                <div class="col-md-4 col-md-offset-1">
                    {{ Form::open(array('route' => 'manage.procedures.store','files' => true)) }}
                        <div class="form-group">
                            {{ Form::label('product', 'Select Recipe', array('class' => 'label-control')) }}
                            {{ Form::select('recipe', $recipes, 0, array('class' => 'form-control')) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('name', 'Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control', 'placeholder' => 'Name of Procudure')) }}
                        </div>
                         <div class="form-group">
                            {{ Form::label('item', 'Item') }}
                            {{ Form::text('item', null, array('class' => 'form-control', 'placeholder' => 'Item')) }}
                        </div>
                        {{ Form::submit('Save', array('class' => 'btn btn-primary btn-block')) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div><!-- /.col-lg-12 -->
    </div><!-- /.row -->
</div><!-- /.container-fluid -->

@stop

app/views/procedures/edit.blade.php
@extends('cms.templates.master')

{{-- TITLE : templates.master --}}
@section('title')
<title>Namnam CMS - Edit Procedure</title>
@stop

{{-- CONTENT AREA : templates.master --}}
@section('content')

    @if($errors->has())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
    @endif

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Edit Procedure</h1>
            <div class="row">
                <div class="col-md-4 col-md-offset-1">
                 {{ Form::open(array('route' => array('manage.procedures.update',$procedure->id),'method' => 'put','files' => true)) }}
                        <div class="form-group">
                            {{-- Form::label('recipe', 'Select Recipe', array('class' => 'label-control')) --}}
                            {{-- Form::select('recipe_id', $recipes, $procedure->recipe_id, array('class' => 'form-control')) --}}
                            {{ Form::hidden('recipe_id', $procedure->recipe_id)}}
                            {{ Form::label('recipe_name', 'Recipe : '.$recipe->recipe_name)}}
                        </div>
                        <div class="form-group">
                            {{ Form::label('name', 'Procedure Name') }}
                            {{ Form::text('name', $procedure->name, array('class' => 'form-control', 'placeholder' => 'Procedure Name')) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('item', 'Procedure') }}
                            {{ Form::textarea('item', $procedure->item, array('class' => 'form-control', 'placeholder' => 'Procedure')) }}
                        </div>
                        {{ Form::submit('Save', array('class' => 'btn btn-primary btn-block')) }}
                        @if(isset($recipe_id))
                            {{Form::hidden('recipe_id', $recipe_id)}}
                        @endif
                    {{ Form::close() }}
                </div>
            </div>
        </div><!-- /.col-lg-12 -->
    </div><!-- /.row -->
</div><!-- /.container-fluid -->

@stop

app/views/procedures/index.blade.php
@extends('cms.templates.master')

{{-- TITLE : templates.master --}}
@section('title')
<title>Namnam CMS - Procedure View All</title>
@stop

{{-- CONTENT AREA : templates.master --}}
@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Procedure Settings <a href="{{ URL::route('manage.procedures.create') }}" class="btn btn-default"> Add New</a></h1>
        </div><!-- /.col-lg-12 -->
        <div class="col-lg-12">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>Recipe Name</th>
                        <th>Item</th>
                        <th>Procedure Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
   				 @foreach ($procedures as $procedure)
                        <tr>
                            <td>{{ Recipe::find($procedure->recipe_id)->recipe_name }}</td>
                            <td>{{ $procedure->item }}</td>
                            <td>{{ $procedure->name }}</td>
                            <td>{{ HTML::linkRoute('manage.procedures.edit','Edit', $procedure->id  )}}</td>
                        </tr>
  				  @endforeach
                </tbody>
            </table>
        </div>
    </div><!-- /.row -->
</div><!-- /.container-fluid -->

@stop

app/views/procedures/show.blade.php
/var/www/namnam/app/views/procedures/show.blade.php